name: "01_IAMRoles" 
on:
  push:
    branches:
      - dev
      - stg
      - prod
  pull_request:
    branches:
      - dev
      - stg
      - prod

jobs:
  Plan_Dev:
    if: github.ref == 'refs/heads/dev'
    uses: am-devops09/gh_multi_env_terraform/.github/workflows/aws_tf_plan.yml@dev
    with:
      path: IAMRoles
      tf_vars_file: dev.tfvars
      gh_environment: dev
    secrets:
    #   cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Deploy_Dev:
    needs: Plan_Dev
    uses: am-devops09/gh_multi_env_terraform/.github/workflows/aws_tf_apply.yml@dev
    with:
      path: IAMRoles
      tf_vars_file: dev.tfvars
      gh_environment: dev
    secrets:
    #   cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # Deploy_stg:

  Plan_stg:
    if: github.ref == 'refs/heads/stg'
    uses: am-devops09/gh_multi_env_terraform/.github/workflows/aws_tf_plan.yml@stg
    with:
      path: IAMRoles
      tf_vars_file: stg.tfvars
      gh_environment: stg
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Deploy_stg:
    needs: Plan_stg
    uses: am-devops09/gh_multi_env_terraform/.github/workflows/aws_tf_apply.yml@stg
    with:
      path: IAMRoles
      tf_vars_file: stg.tfvars
      gh_environment: stg
    # secrets:
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Deploy_prod:
    needs: Plan_prod
    uses: am-devops09/gh_multi_env_terraform/.github/workflows/aws_tf_apply.yml@prod
    with:
      path: IAMRoles
      tf_vars_file: prod.tfvars
      gh_environment: prod
    # secrets:
    #   cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}